# Theme: hexo-theme-Melancholia
# Author: 亦封
# Maintainer: @yife68
# Maintainer-GitHub: https://github.com/yife68# 

# theme - GitHub: https://github.com/yife68/hexo-theme-Melancholia# 
# 

# 主题: hexo-theme-Melancholia
# 作者: 亦封
# 维护人员: @yife68
# 维护人员的GitHub个人地址: https://github.com/yife68# 

# 主题的GitHub个人地址: https://github.com/yife68/hexo-theme-Melancholia



# --------------------------------------
# 配置版本 V0.0.6
# --------------------------------------



# 头部 head 配置
# --------------------------------------

index:
  url: true
  # 是否开启获取页面的url链接显示
  icon:
    favicon:
    seventy_eight:
    # 用于苹果设备的图标 78x78
    one_hundred_and_eighty:
    # 用于苹果设备的图标 180x180
  twitter:
  # 分享平台获取参数
    enable: false
    image:
    # 分享至其他平台时显示的图片摘要
  https: true
  # 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
  version_check: true
  # 每次生成页面后，检测主题是否为最新版本


# 网站站长工具
# --------------------------------------

Website_Tools:
  verify:
  # 网站站长验证
    enable: false
    baidu:
    # 百度搜索资源平台
    # https://ziyuan.baidu.com/
  statistics:
  # 网站统计
    enable: false
    five_one_la:
    # 51LA统计
    # https://v6.51.la/
    baidu:
    # 百度站长统计
    # https://tongji.baidu.com/
  monitor:
  # 网站监控
    enable: false
    perf:


# 顶部菜单栏
# --------------------------------------

nav:
  title: "Melancholia"
  # 菜单栏右上角名称
  menu:
  # 导航栏菜单，可自行增减.
    主站: https://meuicat.com/
    首页: /
    分类: /categories/
    关于: /about/


# 腾讯 CoDesign - icon
# https://codesign.qq.com/
# --------------------------------------

icon:
  key: 1Yyg5ZpD7pZ2lKv
  # CSS链接里中间的key
  # 示例：https://cdn3.codesign.qq.com/icons/是此处的Key/latest/iconfont.css
  iconfont_family: iCat
  iconfont: icon-


# 暗黑模式
# --------------------------------------

darkmode:
  enable: true
  display_mode: light
  # 默认颜色 白天 / 夜晚 【 light / dark 】


# banner书籍栏信息
# --------------------------------------

book:
  cover:
  # 书籍封面
  cover_host_color: '#0093E9'
  # 封面主色调
  cover_assistant_color: '#80D0C7'
  # 封面副色调
  title:
  # 书名
  category: 
  # 书籍类别
    - 示例
    # - 可多标签 （建议不超过4个）
  describe:
  # 书籍简介
    one: 我是书籍介绍描述
    # 此处的简介介绍必须填写
    two:
    # 第二段可选填，留空即不显示第二段的简介介绍
  author: 亦封
  # 作者
  introduce: 山高路遠 看世界 也找自己.
  # 作者介绍
  author_home: https://meuicat.com/
  # 作者主页
  author_img:
  # 作者头像
  completion_status: 0
  # 完结状态 连载中 / 完结 【 0 / 1 】